<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibraryManagementSystemV2.DAL\LibraryManagementSystemV2.DAL.csproj" />
    <ProjectReference Include="..\LibraryManagementSystemV2.Shared\LibraryManagementSystemV2.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
